### ISSUE TITLE
Add support for more devices

### ISSUE THREAD

**Issue by RodrigoCard** [d235j/360Controller#24]
There are a lot of opened issues about supporting new devices #20 #14 #5 #1 #17 and a few messages buried inside other issue's comments.

@bleeq said on #5 he was working on adding new devices.

Someone also made a script to change (the version 0.11 of) the driver to accept a big list of new devices, here: http://forums.macrumors.com/showthread.php?t=636420 (the script https://dl.dropboxusercontent.com/u/14890209/Xbox360Driver0.11ExtraPadSupport.command.zip )

That wont work on signed drivers, I think.

So I think that we should add basic support for these devices, It is apparently easy.

Did you do something about that @bleeq ?
Which file do I look to add support for new devices?

**Comment by RodrigoCard** [comment]
Hello People,
If your controller is on this list http://forums.macrumors.com/showthread.php?t=636420

could you test your controller with this version?
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview2.pkg

Please restart once, if you have used the driver since the last time you boot your computer.

Cheers!

**Comment by diedel** [comment]
Hello RodrigoCard,

I've tested thae above version you posted with my Logitech F710:
1) In Preferences the joystick is recognized and all the buttons work as expected
![captura de pantalla 2015-01-25 a las 19 22 10](https://cloud.githubusercontent.com/assets/10698010/5892681/264e78b0-a4c8-11e4-9bbe-5d0324290773.png)
2) But I've tested it in two applications and their behavior it's strange regarding the button numbering. As an example, in both applications XBMC and openMSX (two SDL 1.x applications), the A button is button 12 and the D-Pad UP button is button 1, thus by default I have to press D-Pad UP to confirm/select and A button to go down :). I've read somewhere that the button numbering is returned by SDL, so maybe SDL is wrong but... according to Joystick And Gamepad Tester application
![captura de pantalla 2015-01-25 a las 19 30 13](https://cloud.githubusercontent.com/assets/10698010/5892841/13ad875e-a4ce-11e4-8ff8-26ee4b47a7a6.png)
The buttons are ok and work as expected, but I noticed that all of them are disordered in a special manner :). The buttons 12, 13, 14, 15 are located in the list entries 1, 2, 3, 4, and the buttons 1, 2, 3, 4 are located in the list entries 12, 13, 14, 15... Coincidence?
When I switch the Logitech F710 to D mode instead of X mode all is OK: XBMC, openMSX and Joystick And Gamepad Tester
![captura de pantalla 2015-01-25 a las 20 05 17](https://cloud.githubusercontent.com/assets/10698010/5892837/05be9e58-a4ce-11e4-9374-dae7b11bd4c5.png)

**Comment by RodrigoCard** [comment]
@diedel  looks like this is an issue in these applications or maybe in SDL itself.
I guess this controller reports its data in a different order than other Xinput devices and some applications depend on the order... maybe. :P

**Comment by RodrigoCard** [comment]
@diedel Soon the driver will be able to reorder its buttons, so this will help you. But I suggest you to use the dinput mode for supported applications anyway. :)

**Comment by RodrigoCard** [comment]
Every device mentioned here was added to the driver's Plist. So I will close this.

If you have a problem with newly added devices or want a new device added to the list, please create a new issue.

:)
