### ISSUE TITLE
Uninstalling the driver

### ISSUE THREAD

**Issue by rmaob** [d235j/360Controller#98]
How does one uninstall this? Need to uninstall to resolve some conflicts before reinstalling

**Comment by IcyTesseract** [comment]
This command should tell you the files related to 360Controller:

```
pkgutil --files com.mice.pkg.Xbox360controller
```

Just copy and paste into the Terminal

**Comment by Deph0** [comment]
There will be an uninstall button inside the preference pane in the new version; as per issue #54.

**Comment by julian-weinert** [comment]
I don't get any files returned by `pkgutil`.
Can you maybe provide a list of files gettimg installed?

**Comment by RodrigoCard** [comment]
this is the command you need:
````
pkgutil --files "com.mice.pkg.Xbox360controller"
````
also, try this driver version first
https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview6.pkg
it can be disabled temporarily and includes an uninstaller.
(you may need to restart once after installation)

**Comment by BCMNG** [comment]
3-4 days ago I wanted to re-install the driver as I'm having issues with a specific game (since their last update).

I'm not able to uninstall:
![xb360_gh_error_1](https://cloud.githubusercontent.com/assets/11871761/8269525/a60bfe18-17ac-11e5-80de-6da200a54f52.png)
![xb360_gh_error_2](https://cloud.githubusercontent.com/assets/11871761/8269526/a60edf84-17ac-11e5-9f81-537f8049ba27.png)

Additional note:
Before installing this ...preview.pkg version (weeks ago), I did not manually uninstalled the previous version. Could this be the reason for the error?


in case the upload doesn't show:
http://i.imgur.com/Uvrg6xM.png
http://i.imgur.com/txlKZRT.png

**Comment by RodrigoCard** [comment]
Enabling and disabling is not that reliable right now.

Please do this:
* remove all xbox hardware connected to your mac
* restart your mac
* uninstall

After that you can install the latest driver and the disable option should work for you. I think :P
If not, at last you uninstalled properly.

Cheers!

**Comment by BCMNG** [comment]
Thanks!
I went with the command you've posted earlier:
pkgutil --files "com.mice.pkg.Xbox360controller"

and installed it again. The issue with the game didn't get solved. I'm waiting for their support to answer (Valve/Steam). Went with Bootcamp now. Feels kinda like a loss :/

btw -> restart/uninstall did not work. Showed the same error-button.
Sadly can't provide anything now to help you guys I guess?

**Comment by masterlui** [comment]
Good Morning from Colombia,. I'd like to know how safe is to install the driver on my mac using the microsoft wireless receiver for my xbox360 controller? here is an screenshot of my system w/ Yosemite 10.10.3
 
![screenshot 2015-06-23 10 56 09](https://cloud.githubusercontent.com/assets/226096/8310647/f873c38e-1996-11e5-809a-7cdfe0849def.png)

**Comment by FranticRain** [comment]
I have an identical computer, it runs just fine. If you can run Yosemite, you can run this driver.

**Comment by masterlui** [comment]
Awesome,. thanks...I'll try again!

**Comment by RodrigoCard** [comment]
I will close this and post the beta soon (for real), thanks!
